name: build

on: [push, pull_request, workflow_dispatch]

env:
  LPRunUrl: https://www.linqpad.net/GetFile.aspx?preview+LINQPad8-Beta.zip
  LPRun: LPRun8-x64.exe --% -fx=9.0
  CompileOnly: -compileonly
  PSHeader: |
    $ErrorActionPreference = 'Stop'
    $Verbose = $VerbosePreference -ne 'SilentlyContinue'
  DoWikiScrape: -compileonly
  PSClearClipboard: |
    '' | Set-Clipboard
  PSAssertClipboard: |
    if(-not $env:DoWikiScrape){
      Get-Clipboard
      if(-not $(Get-Clipboard -Raw).Trim()){ throw "Clipboard is empty" }
    }
  PSAssertClipboardEventStock: |
    if(-not $env:DoWikiScrape){
      Get-Clipboard
      if($(Get-Clipboard).Length -le (4 + 8)){ throw "Event stock parsing failed" }
    }
  PSAssertModules: |
    if(-not $env:DoWikiScrape){
      if((Get-Content -Raw ./data/Operators.tsv).Split("`n", [StringSplitOptions]::RemoveEmptyEntries -bor [StringSplitOptions]::TrimEntries) -join "`n" -ne ($(Get-Clipboard) -join "`n")){
        throw "Modules have been updated"
      }
    }
  ARTIFACT_NAME: LatestCommit
  RETENTION_DAYS: 30

jobs:
  build:
    runs-on: windows-latest

    steps:

      # Set up

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: |
            9.0.x

      # Set up LPRun

      - name: Set up LPRun
        uses: Alex079/setup-custom-tool@v2.0.0
        with:
          archiveUrl: ${{env.LPRunUrl}}

      # Check out

      - name: Check out
        uses: actions/checkout@v4.2.2

      # LPRun scripts

      - name: LPRun EventStatus.linq
        if: ${{success() || failure()}}
        run: ${{env.LPRun}} EventStatus.linq

      - name: LPRun EventStockScraper.linq
        if: ${{success() || failure()}}
        run: |
          ${{env.PSHeader}}
          ${{env.PSClearClipboard}}
          ${{env.LPRun}} ${{env.DoWikiScrape}} EventStockScraper.linq
          ${{env.PSAssertClipboardEventStock}}

      - name: LPRun Hourglass.linq
        if: ${{success() || failure()}}
        run: ${{env.LPRun}} ${{env.CompileOnly}} Hourglass.linq

      - name: LPRun OperationStrategies.linq
        if: ${{success() || failure()}}
        run: ${{env.LPRun}} OperationStrategies.linq

      - name: LPRun OperatorModules.linq
        if: ${{success() || failure()}}
        run: ${{env.LPRun}} OperatorModules.linq

      - name: LPRun OperatorModulesScraper.linq
        if: ${{success() || failure()}}
        run: |
          ${{env.PSHeader}}
          ${{env.PSClearClipboard}}
          ${{env.LPRun}} ${{env.DoWikiScrape}} OperatorModulesScraper.linq
          ${{env.PSAssertClipboard}}
          ${{env.PSAssertModules}}

      - name: LPRun OriginitePrimePacks.linq
        if: ${{success() || failure()}}
        run: ${{env.LPRun}} OriginitePrimePacks.linq

      - name: Archive latest commit
        run: |
          ${{env.PSHeader}}
          # Get latest commit message.
          $message = "Arknights-$((git show-branch --no-name HEAD).Trim() -replace ' event$','' -replace ' ','_')"
          # Export latest commit to the commit message dir.
          git checkout-index -a -f --prefix=./$message/
          # Archive latest commit message dir.
          7z a -tzip -mx=9 $message $message/* '-xr!.github'

      - name: Upload latest commit archive
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: |
            *.zip
          compression-level: 0
          retention-days: ${{env.RETENTION_DAYS}}
